from os import path, makedirs
import accelerate
import numpy as np
from tqdm import tqdm
from torch.utils.data import DataLoader
import json
import gc
import pandas as pd
import torch
import pickle
import zlib

# LOCAL IMPORTS
from hyperprobe.data_creation.utils import emb_utils
    
configs = {
    'model_name': 'meta-llama/Llama-3.1-8B',
    'batch_size': 1
}


def ingest_embeddings(docs:list[str], model_name:str) -> tuple[dict[str, torch.Tensor], tuple[int, int], pd.DataFrame, torch.Tensor]:
    """
    Ingest the embeddings from the LLM.
    """
        
    # (0) Create the dataset and loader
    inputs = emb_utils.InputDataset(docs)
    input_loader = DataLoader(inputs, batch_size = configs['batch_size'], shuffle = True)
    
    # (1a) Load the LLM
    tokenizer, model = emb_utils.load_llm(model_name, dtype = torch.bfloat16)
    median_layer = model.config.num_hidden_layers // 2
    probed_layers = (median_layer, model.config.num_hidden_layers)
    
    # (1c) Load the unembedding layer
    if hasattr(model, 'lm_head'):
        unembedding_layer = model.lm_head
    elif hasattr(model, 'embed_out'):
        unembedding_layer = model.embed_out
    else:
        raise ValueError(f"Unsupported model architecture: {model.config.architectures[0]}")
    
    # Get the tokens for the cutoffs
    #cutoff_tokens = np.array([tokenizer.encode(t, add_special_tokens=False)[0] for t in [' =', ' :']])
    
    # (1b) Create the embeddings
    token_embeddings = dict()
    feature_softmax = dict()
    cluster_stats = list()
    layer_correlations = list()
    for input_batch in tqdm(input_loader, desc = 'Creating embeddings'):
        
        # Remove the target token
        parts = input_batch[0].split()
        partial_doc = ' '+ ' '.join(parts[:-1])
        target_word = parts[-1].lower()
        
        # Tokenize the batch of prompts
        inputs_ids = tokenizer(partial_doc, return_tensors="pt").to(model.device)
        outputs = model(**inputs_ids, output_hidden_states=True)

        # Check if the selected positions are correct
        #tokens = np.array([t.strip('Ġ') for t in tokenizer.convert_ids_to_tokens(inputs_ids.input_ids[0])])

        # Get the position of the last delimiter
        #intra_delimiter_pos = torch.argwhere(inputs_ids.input_ids[0] == cutoff_tokens[1]).squeeze().tolist()
        #if isinstance(intra_delimiter_pos, list):
        #    if len(intra_delimiter_pos) > 1:
        #        intra_delimiter_pos = intra_delimiter_pos[-1]
        #    else:
        #        intra_delimiter_pos = -1
                
        # Extract the hidden states
        hs = torch.stack(outputs.hidden_states).squeeze()
        hs = hs[median_layer:, -1]
        
        # Compute the correlations
        layer_correlations.append(torch.corrcoef(hs).detach().cpu().bfloat16())
        
        # Cluster the hidden states by applying k-means
        cluster_assignments, centroids = emb_utils.kmeans_cuda(hs, K = 5)
        
        # Save the cluster assignments
        cluster_assignments = list(zip(range(median_layer, model.config.num_hidden_layers + 1), cluster_assignments))
        cluster_stats.extend(cluster_assignments)
        
        # Store the embeddings
        token_embeddings[input_batch[0]] = centroids.detach().bfloat16().cpu()
        
        # [AUGMENTATION STATEGY] View the most likely token generated by the model
        last_layer = hs[-1]
        top_token, token_softmax = emb_utils.logit_lens(last_layer, projector = unembedding_layer, tokenizer = tokenizer)

        # Store the embeddings if the top token is the last word
        if top_token == target_word:
            
            # Check if the top token is already in the features
            if target_word in feature_softmax.keys() and token_softmax < feature_softmax[target_word]:
                continue
            
            # Store the embeddings
            token_embeddings[target_word] = last_layer.detach().bfloat16().cpu()
            feature_softmax[target_word] = token_softmax

    # Free the GPU memory and delete all variables
    del model, tokenizer, inputs_ids, outputs, hs, last_layer, cluster_assignments, centroids, feature_softmax, unembedding_layer, input_loader, inputs, input_batch, partial_doc, target_word, top_token, token_softmax

    # Perform garbage collection and clear CUDA memory
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    torch.cuda.reset_accumulated_memory_stats()
    torch.cuda.reset_peak_memory_stats()
    gc.collect()
   
    return token_embeddings, probed_layers, cluster_stats, layer_correlations

if __name__ == '__main__':
    
    print(f'GPUs ({torch.cuda.device_count()}):\n' + '\n'.join([torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())]))
    
    # Load the data --> texts | random_pairs | reversed_mixed_texts | features
    input_data_path = path.join('data', 'splitted_data.json')
    with open(input_data_path, mode = "r") as file:
        examples = json.load(file)
    examples = [item for items in examples.values() for item in items]
    
    examples = np.random.choice(examples, size = 10000, replace = False).tolist()

    # Ingest the embeddings
    token_embeddings, probed_layers, cluster_stats, layer_correlations = ingest_embeddings(examples, configs['model_name'])

    # Stack the cluster stats
    cluster_stats = pd.DataFrame(cluster_stats, columns = ['layer', 'cluster'])
    correlations = torch.stack(layer_correlations)
    
    # (1) Create the output folder
    dataset_name = path.basename(input_data_path).split('.')[0].split('_')
    main_folder_name = dataset_name[0].lower() + ''.join(word.capitalize() for word in dataset_name[1:])
    version_name = f'clustered_L{probed_layers[0]}_L{probed_layers[1]}'
    output_folder = path.join('outputs', 'embeddings', main_folder_name, version_name)
    makedirs(output_folder, exist_ok=True)
    
    # (2) Save the embeddings
    print('\nSaving the embeddings...\n')
    
    # Save the embeddings
    with open(path.join(output_folder, 'embeddings.pkl.zlib'), mode = "wb") as file:
        file.write(zlib.compress(pickle.dumps(token_embeddings, protocol=pickle.HIGHEST_PROTOCOL), level = 9))
            
    # Save the cluster stats
    emb_utils.plot_cluster(cluster_stats, output_folder)
    emb_utils.plot_correlations(correlations, output_folder, starting_layer_label=probed_layers[0])
    
    # Print the results
    print(f'\nOK: Saved the embeddings for {len(examples)} inputs --> config: {configs}\n')